# This file is used to define the services that will be used in the application.
name: mern-app

services:
  # MongoDB
  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  # Client
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api
  # API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - 5000:5000
    depends_on:
      - mongo

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge
